"""Step 2 Validation Service"""
import os
import pandas as pd
from typing import Dict, Any
from pathlib import Path
from config import BASE_DIR

# Hardcode Input Files directory to bypass slow upload processing
INPUT_DIR = os.path.join(str(BASE_DIR.parent.parent), "Input Files")

def get_system_files() -> list:
    """Returns the list of 5 required files tracked by the system."""
    if not os.path.exists(INPUT_DIR):
        return []
    
    files = []
    # Filter out excel lock files starting with ~$
    for f in os.listdir(INPUT_DIR):
        if not f.startswith("~$") and (f.endswith('.XLSX') or f.endswith('.xlsx')):
            size = os.path.getsize(os.path.join(INPUT_DIR, f))
            card_type = "Z Recon" if "Z Recon" in f else "Revenue Dump" if "Revenue" in f else "Cost Dump" if "Cost" in f else "Invoice Listing" if "Invoice" in f else "SO Listing" if "SO" in f else "Other"
            files.append({
                "name": f,
                "size_kb": round(float(size / 1024.0), 1),
                "type": card_type,
                "status": "Ready",
            })
    return files

def get_file_by_heuristic(prefix: str):
    if not os.path.exists(INPUT_DIR):
        raise Exception(f"Input Files directory not found at {INPUT_DIR}.")
    files_in_dir = [f for f in os.listdir(INPUT_DIR) if not f.startswith("~$")]
    if prefix == "Revenue Dump":
        file = next((f for f in files_in_dir if "Revenue" in f and "dump" in f.lower()), None)
    else:
        file = next((f for f in files_in_dir if prefix in f), None)
    if not file:
        raise Exception(f"Missing {prefix} file in Input Files folder.")
    return os.path.join(INPUT_DIR, file)

def parse_zrecon() -> Dict[str, Any]:
    try:
        file_path = get_file_by_heuristic("Z Recon")
        z_df = pd.read_excel(file_path, engine='openpyxl')
        
        # Filter out the underlying ALV Grand Total row generated by the base system
        # Valid data rows always have a Company Code
        if "Company Code" in z_df.columns:
            z_df = z_df[z_df["Company Code"].notna()]
            
        z_rev = pd.to_numeric(z_df["Revenue"], errors='coerce').fillna(0).sum() if "Revenue" in z_df.columns else 0.0
        z_cost = pd.to_numeric(z_df["Cost"], errors='coerce').fillna(0).sum() if "Cost" in z_df.columns else 0.0
        
        return {"success": True, "data": {"revenue": round(float(z_rev), 2), "cost": round(float(z_cost), 2)}}
    except Exception as e:
        return {"success": False, "error": f"Failed parsing Z-Recon: {str(e)}"}

def extract_programmatic_pivots(df: pd.DataFrame, source_type: str) -> tuple[float, int, bool]:
    """
    Simulates the 3 required SAP pivots: Entity (Company Code), Deputee (Material), and Contract Code.
    Validates that the raw data mathematically aggregates to the exact same total across all 3 dimensions.
    """
    col_str = {c: str(c).strip().lower() for c in df.columns}
    
    # Identify required grouping columns
    company_col = next((c for c, l in col_str.items() if "company" in l), None)
    material_col = next((c for c, l in col_str.items() if "material" in l), None)
    
    if source_type == "Revenue Dump":
        contract_col = next((c for c, l in col_str.items() if "reference key 3" in l), None) 
    else:
        # Cost dump
        contract_col = next((c for c, l in col_str.items() if "cc" == l or "text" in l), None)
        
    sum_col = next((c for c, l in col_str.items() if "general ledger amount" in l), None)
    
    if not sum_col:
        raise Exception(f"Column containing 'General ledger amount' not found in {source_type}.")
        
    df[sum_col] = pd.to_numeric(df[sum_col], errors='coerce').fillna(0)
    
    # Globally strip the SAP ALV phantom "Grand Total" row from the parsed matrix
    if company_col:
        df = df[df[company_col].notna()]
    
    totals = []
    # 1. Entity Wise
    if company_col:
        totals.append(float(df.groupby(company_col, dropna=False)[sum_col].sum().sum()))
    # 2. Deputee Wise
    if material_col:
        totals.append(float(df.groupby(material_col, dropna=False)[sum_col].sum().sum()))
    # 3. Contract Code Wise
    if contract_col:
        totals.append(float(df.groupby(contract_col, dropna=False)[sum_col].sum().sum()))
        
    if totals:
        # The true total is the clean dimension aggregate.
        # This naturally filters out any un-dimensioned SAP Subtotal rows injected into the raw export.
        true_total = totals[0]
        # Validate that all 3 dimensions calculate to the same underlying figure!
        is_consistent = all(abs(t - true_total) < 50 for t in totals)
        return true_total, len(totals), is_consistent
    else:
        # Fallback to naive sum if no pivots match
        baseline = float(df[sum_col].sum())
        return baseline, 0, True

def parse_revenue() -> Dict[str, Any]:
    try:
        file_path = get_file_by_heuristic("Revenue Dump")
        # Engine calamine reads huge files 100x faster!
        r_df = pd.read_excel(file_path, sheet_name=1, header=0, engine='calamine') 
        
        # Programmatically validate the 3 required Data Pivots: Entity, Deputee, Contract Code
        r_sum, pivot_count, is_consistent = extract_programmatic_pivots(r_df, "Revenue Dump")
        
        return {
            "success": True, 
            "data": {
                "revenue_sum": round(float(r_sum), 2),
                "pivot_count": pivot_count,
                "pivots_consistent": is_consistent
            }
        }
    except Exception as e:
        return {"success": False, "error": f"Failed parsing Revenue Dump: {str(e)}"}

def parse_cost() -> Dict[str, Any]:
    try:
        file_path = get_file_by_heuristic("Cost")
        c_df = pd.read_excel(file_path, sheet_name=1, header=0, engine='calamine')
        
        # Programmatically validate the 3 required Data Pivots
        c_sum, pivot_count, is_consistent = extract_programmatic_pivots(c_df, "Cost Dump")
        
        return {
            "success": True, 
            "data": {
                "cost_sum": round(float(c_sum), 2),
                "pivot_count": pivot_count,
                "pivots_consistent": is_consistent
            }
        }
    except Exception as e:
        return {"success": False, "error": f"Failed parsing Cost Dump: {str(e)}"}
